source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
target "DemoMHealth" do
    pod 'MBProgressHUD', '~> 0.9'
    pod 'AFNetworking', '~> 3.0'
    pod 'JSONModel'
    pod 'MagicalRecord', '~> 2.3'
    
end